### ISSUE TITLE
NEOS GAMS bug

### ISSUE THREAD

**Issue by gnowzil** [fruchtfolge/neos-js#7]
Hi, I'm with the NEOS team.  We got a report about GAMS jobs not working now when submitted via neos-js.  It looks like neos-js submits files with a few blank lines for the optional inputs.  We recently added a feature for an optional restart file.  It looks like that's causing the error because GAMS tries to restart from the blank file.  If possible, it would be best if nothing is submitted for optional inputs unless there is actually information that needs to be passed in.

**Comment by chrispahm** [comment]
Hi, thanks for opening the issue!
The `0.1.0` version of `neos-js` fixes the issue with the blank lines being additionally submitted. 
Furthermore, a new method called `xmlstring` was added to the package, which turns a JavaScript object including optional inputs into a NEOS compatible string:

```js
NEOS.xmlstring({
  category: 'LP',
  solver: 'CPLEX',
  inputMethod: 'GAMS',
  model: simulationModelString,
  // wantGDX, or other optional inputs
  email: 'your@email.com'
})
.then(NEOS.submitJob)
.then(NEOS.getFinalResults)
.then(res => {
  // work with the resulting listing file
})
.catch(err => {
  // catch errors
})
```

Please let me know if the issue persists (or other issues appear)!
